"""The doctor directory: who to contact, per specialty.

⚠️  THE DATA THAT SHIPS HERE IS FAKE, ON PURPOSE  ⚠️

Every entry generated by this module is a placeholder with an unusable phone
number (+91 00000 000NN) and `is_placeholder: True`, which the frontend renders
as a visible warning badge on the card.

That is a deliberate choice, not an oversight. A realistic-looking phone number
in a triage app is dangerous in two directions: someone having a heart attack
could call it and reach nobody, and an invented name and number could belong to
a real person who then fields medical calls. So the directory ships empty of real
data and refuses to pretend otherwise.

To put real doctors in
----------------------
Copy doctors.example.json to doctors.json in this folder and edit it. That file
is gitignored, so private contact details never land in version control. The
placeholders disappear as soon as doctors.json exists.

Photos: set "photo" to a URL or a path the frontend can reach. Leave it null and
the UI draws initials in a coloured circle instead, which looks deliberate rather
than broken. Do not add a photo of anyone without their permission.
"""

import json
import logging
import os
from typing import Dict, List, Optional

import hours
from specialties import SPECIALTIES

log = logging.getLogger(__name__)

_HERE = os.path.dirname(os.path.abspath(__file__))
DOCTORS_FILE = os.path.join(_HERE, "doctors.json")

# Every field a doctor card can display. Anything missing from doctors.json is
# filled with None so the frontend never has to guard against absent keys.
FIELDS = (
    "id",
    "name",
    "specialty",
    "qualification",
    "hospital",
    "city",
    "phone",
    "whatsapp",
    "assistant_name",
    "assistant_phone",
    "email",
    "timings",
    "languages",
    "photo",
    "lat",
    "lng",
)

# Rough bounds, only to catch swapped or mistyped coordinates. A doctor whose
# latitude and longitude are the wrong way round would otherwise be placed in
# the sea and shown as "4,000 km away", which reads like a broken app rather
# than a bad data entry.
LAT_RANGE = (-90.0, 90.0)
LNG_RANGE = (-180.0, 180.0)


def _parse_coordinate(value, low: float, high: float) -> Optional[float]:
    """A usable coordinate, or None. Never raises on junk input."""
    if value is None or value == "":
        return None
    try:
        number = float(value)
    except (TypeError, ValueError):
        return None
    if not (low <= number <= high):
        return None
    return number


# Placeholders get real opening hours but no coordinates, and the split is
# deliberate. Hours are harmless to invent -- they let the open/closed badges be
# seen working -- whereas a made-up location would put a fake doctor on a map and
# tell someone a clinic is 2 km away when nothing is there. Coordinates stay
# null until a real address is entered.
_PLACEHOLDER_HOURS = {
    day: [["10:00", "13:00"], ["17:00", "20:00"]]
    for day in ("mon", "tue", "wed", "thu", "fri", "sat")
}


def _placeholder(specialty_id: str, index: int, serial: int) -> Dict:
    """One obviously-fake directory entry for a specialty.

    Generated rather than hand-written so that nothing in this file can be
    mistaken for real contact data, and so adding a specialty does not mean
    writing out another two entries by hand.
    """
    specialty = SPECIALTIES[specialty_id]
    # Placeholders skip _normalise, so the hours are converted here instead —
    # everything downstream expects the parsed form, not the raw JSON one.
    parsed_hours = hours.normalise(
        {"always_open": True}
        if specialty_id == "emergency_medicine"
        else _PLACEHOLDER_HOURS
    )
    return {
        "id": f"placeholder-{specialty_id}-{index}",
        "name": f"Dr. {specialty.name} {index}",
        "specialty": specialty_id,
        "qualification": "Add qualification",
        "hospital": "Add hospital or clinic name",
        "city": "Add city",
        # Reserved unusable numbers. Not dialable, and visibly not a real number.
        "phone": f"+91 00000 {serial:05d}",
        "whatsapp": f"+91 00000 {serial:05d}",
        "assistant_name": "Add assistant name",
        "assistant_phone": f"+91 00000 {serial + 1:05d}",
        "email": "add-email@example.com",
        "languages": ["Add languages"],
        "photo": None,
        "lat": None,
        "lng": None,
        # Emergency departments never close; everyone else keeps clinic hours.
        "hours": parsed_hours,
        "timings": hours.describe(parsed_hours),
        "is_placeholder": True,
    }


def _build_placeholders() -> List[Dict]:
    entries = []
    serial = 1
    for specialty_id in SPECIALTIES:
        for index in (1, 2):
            entries.append(_placeholder(specialty_id, index, serial))
            serial += 2
    return entries


def _normalise(entry: Dict, position: int) -> Optional[Dict]:
    """Fill in missing fields and reject entries that cannot be displayed.

    A directory entry with no name or an unknown specialty would render as an
    empty card, so it is dropped with a warning rather than shown. Anything else
    missing is tolerated -- a doctor with no listed assistant is still useful.
    """
    name = str(entry.get("name") or "").strip()
    if not name:
        log.warning("Skipping doctors.json entry %d: no name.", position)
        return None

    specialty_id = str(entry.get("specialty") or "").strip()
    if specialty_id not in SPECIALTIES:
        log.warning(
            "Skipping %r: specialty %r is not one of %s.",
            name,
            specialty_id,
            ", ".join(SPECIALTIES),
        )
        return None

    normalised = {field: entry.get(field) for field in FIELDS}
    normalised["name"] = name
    normalised["specialty"] = specialty_id
    normalised["id"] = str(entry.get("id") or f"doctor-{position}")

    languages = entry.get("languages")
    if isinstance(languages, str):
        # Tolerate "English, Hindi" as well as a proper list.
        languages = [part.strip() for part in languages.split(",") if part.strip()]
    normalised["languages"] = languages or []

    normalised["lat"] = _parse_coordinate(entry.get("lat"), *LAT_RANGE)
    normalised["lng"] = _parse_coordinate(entry.get("lng"), *LNG_RANGE)
    # Both or neither. Half a coordinate cannot be placed anywhere, and keeping
    # it would let the frontend compute a distance from a longitude of zero --
    # a point in the Atlantic that every Indian clinic is 6,000 km from.
    if normalised["lat"] is None or normalised["lng"] is None:
        normalised["lat"] = normalised["lng"] = None

    normalised["hours"] = hours.normalise(entry.get("hours"))
    if normalised["hours"] and not normalised.get("timings"):
        # Fill the human-readable line from the structured hours when the
        # directory only supplied one of the two.
        normalised["timings"] = hours.describe(normalised["hours"])

    normalised["is_placeholder"] = bool(entry.get("is_placeholder", False))
    return normalised


def _load() -> List[Dict]:
    """Load doctors.json, falling back to placeholders.

    Never raises. A malformed doctors.json logs a warning and falls back, because
    a broken directory file should not take the triage endpoint down with it --
    the urgency advice is the part that matters most.
    """
    if not os.path.exists(DOCTORS_FILE):
        log.info(
            "No doctors.json found — serving placeholder directory entries. "
            "Copy doctors.example.json to doctors.json to add real contacts."
        )
        return _build_placeholders()

    try:
        # utf-8-sig, not utf-8: Notepad and several Windows editors write a
        # byte-order mark, and plain utf-8 rejects it. That failure is silent --
        # the directory falls back to placeholders and the person who just
        # entered forty real doctors has no idea why none of them appear.
        # utf-8-sig reads files with or without the mark.
        with open(DOCTORS_FILE, encoding="utf-8-sig") as handle:
            raw = json.load(handle)
    except (OSError, json.JSONDecodeError) as exc:
        log.warning("Could not read %s (%s) — using placeholders.", DOCTORS_FILE, exc)
        return _build_placeholders()

    # Accept either a bare list or {"doctors": [...]}.
    if isinstance(raw, dict):
        raw = raw.get("doctors", [])
    if not isinstance(raw, list):
        log.warning("%s should contain a list of doctors — using placeholders.", DOCTORS_FILE)
        return _build_placeholders()

    entries = []
    for position, entry in enumerate(raw, start=1):
        if not isinstance(entry, dict):
            log.warning("Skipping doctors.json entry %d: not an object.", position)
            continue
        normalised = _normalise(entry, position)
        if normalised:
            entries.append(normalised)

    if not entries:
        log.warning("%s had no usable entries — using placeholders.", DOCTORS_FILE)
        return _build_placeholders()

    return entries


DOCTORS: List[Dict] = _load()


def using_placeholders() -> bool:
    """True while the directory is still sample data.

    The frontend uses this to show a banner over the whole directory, so nobody
    demoing the app can mistake the sample entries for real contacts.
    """
    return any(d.get("is_placeholder") for d in DOCTORS)


def for_specialty(specialty_id: str) -> List[Dict]:
    """Doctors in one specialty."""
    return [d for d in DOCTORS if d["specialty"] == specialty_id]


def all_doctors() -> List[Dict]:
    return list(DOCTORS)


def counts_by_specialty() -> Dict[str, int]:
    """How many doctors are listed per specialty, for the filter chips."""
    counts = {specialty_id: 0 for specialty_id in SPECIALTIES}
    for doctor in DOCTORS:
        counts[doctor["specialty"]] = counts.get(doctor["specialty"], 0) + 1
    return counts
